---
- hosts: localhost
  connection: local
  become: true
  tags: freedom

  pre_tasks:
    - name: pre-run | update repositories (debian, etc)
      tags: always
      apt: update_cache=yes state=latest
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Kali"]

    - name: pre-run | update repositories (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update repositories (RHEL)
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_os_family == "RedHat"

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/whoami.yml
    - include: tasks/emacs.yml
    - include: tasks/desktop-apps.yml
    - include: tasks/whoami.yml
    - include: tasks/synodrive.yml
    - include: tasks/brave-browser.yml
    - include: tasks/gnome.yml
    - include: tasks/docker.yml
    - include: tasks/dev-apps.yml
    - include: tasks/1password.yml

# - hosts: localhost
#   connection: local
#   become: no

#   tasks:
#     - include: tasks/whoami.yml

- hosts: localhost
  connection: local
  tags: shell
  become: yes
  become_user: "{{ remote_regular_user }}"

  tasks:
    - include: tasks/ohmyzsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/doom-emacs.yml
    - include: tasks/fonts.yml
    - include: tasks/wallpapers.yml
