---
- hosts: localhost
  connection: local
  become: true
  tags: always

  pre_tasks:
    - name: pre-run | update repositories (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

    - name: pre-run | update repositories (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml

- hosts: localhost
  connection: local
  become: no
  # become_user: "{{ ansible_user_id }}"
  # become_user: "{{ lookup('env', 'USER') }}"
  become_user: "{{ login_user }}"

  tasks:
    - include: tasks/whoami.yml
    - include: tasks/ohmyzsh.yml
    - include: tasks/dotfiles.yml
