---
- hosts: localhost

  tasks:
#    - include_tasks: tasks/whoami.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/mas.yml
    - include_tasks: tasks/macemacs.yml


- hosts: localhost
  connection: local
  tags: shell
  become: no
#  become_user: "{{ remote_regular_user }}"

  tasks:
    - include_tasks: tasks/ohmyzsh.yml
    - include_tasks: tasks/dotfiles.yml
