---
- name: fetching 1password gpg key for apt (Ubuntu/Pop_OS!)
  ansible.builtin.get_url:
    url: "https://downloads.1password.com/linux/keys/1password.asc"
    dest: /usr/share/keyrings/1password.asc
#  when: ansible_pkg_mgr == 'apt'
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: Adding 1password apt sources list for AMD64 (Ubuntu/Pop_OS!)
  apt_repository:
   # repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
    state: present
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"] #and ansible_architecture == "amd64")

- name: Installing 1password packages with apt
  apt:
    name:
      - 1password
    state: present
  when: ansible_pkg_mgr == 'apt'
