---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg
  when: ansible_pkg_mgr == 'apt'

- name: Add an apt signing key
  apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
  when: ansible_pkg_mgr == 'apt'

- name: Add apt repo
  apt_repository:
    repo: deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} main
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Install package
  apt:
    name:
      - crowdsec
  when: ansible_pkg_mgr == 'apt'
