---
- name: Install Desktop applications (APT)
  apt:
    pkg:
      - gnome-tweaks
      - flameshot
      - vlc
      - gnupg
      - jq
      - python3-psutil
      - transmission
      - audacious
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install Desktop applications (RHEL)
  dnf:
    pkg:
      - gnome-tweaks
      - flameshot
      - vlc
      - gnupg
      - jq
      - python3-psutil
      - transmission
      - audacious
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'dnf'
