---
- name: Install Developer applications
  apt:
    pkg:
      - golang-go
      - vagrant
      - awscli
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select

- name: Install Virtualization (virtualbox) applications
  apt:
    pkg:
      - virtualbox
      - virtualbox-ext-pack
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'


# - name: fetching virtualbox gpg-asc key for apt (Ubuntu/Pop_OS!)
#   apt_key:
#     url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
#     state: present
# #  when: ansible_pkg_mgr == 'apt'
#   when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

# - name: fetching virtualbox gpg-asc key for apt (Ubuntu/Pop_OS!)
#   apt_key:
#     url: "https://www.virtualbox.org/download/oracle_vbox.asc"
#     state: present
# #  when: ansible_pkg_mgr == 'apt'
#   when: ansible_distribution in ["Ubuntu", "Pop!_OS"]
