---
- name: Downloading Dotfiles
  git:
    repo: https://github.com/ciph3rz/dotfiles.git
    dest: ~/code/dotfiles
    version: linux

- name: Symlinking dotfiles
  script: ~/code/dotfiles/make-symlinks.sh
