---
- name: Install Emacs and key dependancies (APT)
  apt:
    pkg:
      - golang
      - shellcheck
      - cmake
      - xclip
      - graphviz
      - python3-proselint
      - fd-find
      - ripgrep
      - emacs
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install Emacs and key dependancies (RHEL)
  apt:
    pkg:
      - golang
      - shellcheck
      - cmake
      - xclip
      - graphviz
      - python3-proselint
      - fd-find
      - ripgrep
      - emacs
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install Emacs and key dependancies (Arch)
  pacman:
    name:
      - go
      - shellcheck
      - cmake
      - xclip
      - graphviz
      # - python3-proselint
      - fd
      - ripgrep
      - emacs
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'pacman'
