---
- name: Install Emacs dependancies for Emacs compilation
  apt:
    pkg:
      - autoconf
      - automake
      - autotools-dev
      - bsd-mailx
      - build-essential
      - diffstat
      - gnutls-dev
      - imagemagick
      - libasound2-dev
      - libc6-dev
      - libdatrie-dev
      - libdbus-1-dev 
      - libgconf2-dev
      - libgif-dev
      - libgnutls28-dev 
      - libgpm-dev 
      - libgtk2.0-dev 
      - libgtk-3-dev
      - libice-dev 
      - libjpeg-dev 
      - liblockfile-dev 
      - liblqr-1-0 
      - libm17n-dev 
      - libmagickwand-dev 
      - libncurses5-dev 
      - libncurses-dev 
      - libotf-dev 
      - libpng-dev 
      - librsvg2-dev 
      - libsm-dev 
      - libthai-dev 
      - libtiff5-dev 
      - libtiff-dev 
      - libtinfo-dev 
      - libtool
      - libx11-dev 
      - libxext-dev 
      - libxi-dev 
      - libxml2-dev 
      - libxmu-dev 
      - libxmuu-dev 
      - libxpm-dev
      - libxrandr-dev 
      - libxt-dev 
      - libxtst-dev 
      - libxv-dev 
      - quilt 
      - sharutils 
      - texinfo 
      - xaw3dg 
      - xaw3dg-dev 
      - xorg-dev 
      - xutils-dev 
      - zlib1g-dev 
      - libjansson-dev 
      - libxaw7-dev
      - libselinux1-dev
      - libmagick++-dev 
      - libacl1-dev 
      - gir1.2-javascriptcoregtk-4.0
      - gir1.2-webkit2-4.0 
      - libglvnd-core-dev 
      - libicu-le-hb-dev
      - libidn2-0-dev 
      - libjavascriptcoregtk-4.0-dev 
      - liboss4-salsa2 
      - libsoup2.4-dev 
      - libsystemd-dev 
      - libwebkit2gtk-4.0-dev 
      - libx11-xcb-dev 
      - libxcb-dri2-0-dev 
      - libxcb-dri3-dev
      - libxcb-glx0-dev 
      - libxcb-present-dev 
      - libxshmfence-dev
      - x11proto-composite-dev 
      - x11proto-core-dev 
      - x11proto-damage-dev 
      - x11proto-fixes-dev 
      - libvterm-dev 
      - golang 
      - shellcheck 
      - cmake 
      - xclip 
      - graphviz 
      - python3-proselint 
      - fd-find 
      - ripgrep
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Downloading Emacs Source from GNU.org
  get_url: 
    url: https://ftp.gnu.org/pub/gnu/emacs/emacs-27.2.tar.gz
    dest: /tmp/emacs-27.2.tar.gz
    mode: 0755

- name: Extract Emacs
  ansible.builtin.unarchive:
    src: /tmp/emacs-27.2.tar.gz
    dest: /tmp/

- name: Configuring Emacs
  command: chdir=/tmp/emacs-27.2/ ./configure --with-mailutils

- name: Build Emacs
  make:
    chdir: /tmp/emacs-27.2/

- name: Run Install Emacs
  make:
    chdir: /tmp/emacs-27.2/
    target: install
  become: yes

- name: Cleanup files
