---
- name: Install Neovim
  apt:
    pkg:
      - neovim 
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install Neovim
  pacman:
    name:
      - neovim
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'pacman'

- name: Cloning NVchad ~/.config/nvim directory
    git:
      repo: https://github.com/NvChad/NvChad
      dest: "/Users/{{ lookup('env', 'USER') }}/.config/nvim"



