---
- name: Install packages
  apt:
    name:
    - htop
    - vim
    - tmux
    - zsh
    - git
    - sudo
    - curl
    - wget
    - locate
    - fonts-hack-ttf
    - file
    - jq
    - neofetch
    - lolcat
