---
- name: Install APT packages
  tags: core
  apt:
    name:
    - htop
    - vim
    - tmux
    - zsh
    - git
    - sudo
    - curl
    - wget
    - locate
    - fonts-hack-ttf
    - file
    - jq
    - neofetch
    - lolcat
    - figlet
    - python3
    - python3-venv
    - python3-pip
    - lsb-release
    - ripgrep
    - bat
    - exa
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install RHEL packages
  tags: core
  dnf:
    name:
    - htop
    - vim
    - tmux
    - zsh
    - git
    - sudo
    - curl
    - wget
    - locate
    # - fonts-hack-ttf
    - file
    - jq
    - neofetch
    - lolcat
    - figlet
    - python3
    - python3-devel
    - python3-pip
    - redhat-lsb-core
    - ripgrep
    - bat
    - exa
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'dnf'

- name: Install Pacman packages
  tags: core
  pacman:
    name:
    - htop
    - vim
    - tmux
    - zsh
    - git
    - sudo
    - curl
    - wget
    - locate
    - file
    - jq
    - neofetch
    - lolcat
    - figlet
    - python3
    # - python3-devel
    - python-pip
    - redhat-lsb-core
    - ripgrep
    - bat
    - exa
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'pacman'
