---
- name: Create Ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: make ssh directory
  file:
    path: "/home/ansible/.ssh"
    state: directory

- name: create empty file
  file:
    path: "/home/ansible/.ssh/authorized_keys"
    state: touch

- name: put pubkey
  lineinfile:
    path: "/home/ansible/.ssh/authorized_keys"
    line: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPm1rYilAnL+mUjAvym2LuJwFYbrajkHtoXWNfjwPjqJ ansible}}"
    owner: ansible
    group: ansible
    mode: 0644
