---
- name: Install Zabbix Agent
  apt:
    pkg:
      - zabbix-agent
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install Zabbix Agent (Arch)
  pacman:
    name:
      - zabbix-agent

    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'pacman'

- name: Copy Zabbix Configuration to /etc/zabbix/
  ansible.builtin.copy:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart service zabbix agent
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: zabbix-agent